### PR TITLE
Use `null` instead of `""` for undefined strings

### PR DESCRIPTION
**Pull request by spiffyjr**

### CODE REVIEW

**Comment by spiffyjr** [comment]
This is a PR for #35.

**Comment by bedag-moo** [comment]
I am not sure I like that change as "" makes it easier to fill in a translation than null. 

To have a fallback for untranslated strings, I work as follows:

1. do code changes
2. initiate translation
  a. run ngx-translate-extract
  b. send files to translator
  c. revert the changes
3. once translation is done, I commit the translated file, and repeat step 2 if there were changes in the mean time. 

BTW, I already tried solving this from the other end and had my PR rejected: https://github.com/ngx-translate/core/issues/487

**Comment by spiffyjr** [comment]
Yes, but "" is picked up as translated so the text shows up as "" whereas null will show the proper fallback language/key.

**Comment by bedag-moo** [comment]
I know, which is why I do not check "" into version control, so it's never occurs in production :-)

And thereby I have the best of both worlds: Easy to fill in translations, and proper fallbacks in production.

**Comment by 0x6e68** [comment]
What is the progress with this pull request?

**Pull request closed without merging**
