### PR TITLE
Support for component-translated attributes

### LINKED ISSUE #56: Support for component-translated attributes
I have a component whose attributes must always be translated:

```
<form-control label="Subject" help="A short description of your issue">
```

I'd like a way to tell ngx-translate-extract that these two properties always contain translated texts, so it can extract them.

I know I could move translation outside the component:

```
<form-control label="{{'Subject' | translate}}" help="{{'A short description of your issue' | translate}}">
```

but the nested brackets are cumbersome to get right, and the redundancy clearly harms readability.

### PR DESCRIPTION
**Pull request by bedag-moo**
Fixes #56.

### CODE REVIEW

**Comment by bedag-moo** [comment]
@biesbjerg: It's been a month ... have you seen this PR?

**Comment by bedag-moo** [comment]
@biesbjerg: Could you make a decision whether you'll merge this? So far, I haven't published my changes to the NPM registry because I did not want to clutter their repo, but if you remain unresponsive I guess a fork and separate NPM package will be my only option.

**Comment by biesbjerg** [comment]
Hi @bedag-moo,

Sorry about the late reply. I won't be merging this because I personally don't see the value of always extracting attributes with certain names. You should use the ' TranslatePipe'  to mark attributes translatable imo. Feel free to fork and publish your own package on NPM if you think it will help other.

**Comment by bedag-moo** [comment]
Thanks for replying. 

My use case is that I have a component with 3 attributes, all of which will be translated as a matter of policy. Since we wrap every form elements in this component, adding 3 translate pipes each time would severely clutter up our source code. (That'll easily be several hundred pipe applications per app, and easily thousands across all our apps). So modifying ngx-translate really is the easier solution for me, and possibly others. 

But of course, this is your call to make; I'll see about setting up this fork then.

And BTW: Thanks for the great library, it's a real time saver!

**Pull request closed without merging**
