### PR TITLE
search for TranslateService also in class properties

### PR DESCRIPTION
**Pull request by cvaliere**
instead of searching only in the constructor, search also in the properties of the class

fix notably https://github.com/biesbjerg/ngx-translate-extract/issues/83

### CODE REVIEW

**Comment by vtolstov** [comment]
??

**Comment by cvaliere** [comment]
what's this "??" for?

**Comment by vtolstov** [comment]
i need this feature too =)

**Comment by biesbjerg** [comment]
This is fixed in the next version. Unfortunately I wasn't able to merge your PR because of refactoring of the code, but thanks!

**Comment by cvaliere** [comment]
thanks for the new version; didn't try it yet, but I appreciate your effort :)

**Pull request closed without merging**
